### ISSUE TITLE
Click People to Battle

### ISSUE THREAD

**Issue by brandy** [milan102/Yugioh-Duel-Links-Bot#2]
What are you using to click the people to start the battles? I'm new to c# and looking at the code real quick I cant seem to find which image you're using to select the people to start the battles?

I'm looking to contribute and update the project :)

**Comment by AchmadFathoni** [comment]
I made an active bot project for PC at `https://github.com/AchmadFathoni/Duellink-PC-Bot`. Its still far for complete but I promise to update it every three days.

**Comment by milanify** [comment]
Previously I used images of the people (duelist NPCs) to start the battle, but found that the images weren't working because of the different image sizes based on how far away the NPC was on the screen. Basically using the exact pixels in the pictures of the duelists proved to be inefficient and buggy. 

The bot, when it was working, used color detection to set the start point of where it will click. Then it clicked horizontally across the screen, hoping to pick up a duelist, item, or whatever. It then detected when the "Duel" button is showing (meaning a NPC was clicked) and clicks on that button, then goes through the duel by finding the auto-duel button and waiting for the duel to end.
